### ISSUE TITLE
原型设计，队员估计任务难度并学习必要的技术

### ISSUE THREAD

**Issue by computer-rookie-master** [ChatTom-cats/ChatTom#3]

**Comment by Hlq0710** [comment]
后端编写主要用Java，主要框架springboot，数据库需要用到jdbc和mybaits，mybaits以映射sql语句orm方式来数据库持久化操作。

**Comment by Xguo-ougX** [comment]
随着科技发展，越来越多人跟别人的沟通变少，因此，我们团队开发ChatTom聊天机器人，你可以跟它说任何话，可以跟它诉苦也可以分享喜悦，同时它也提供其他的娱乐方式。本次难度相对较大，需要学习新的前端技术，如React以及了解微信小程序开发。

**Comment by gsoidgsug** [comment]
后端编写主要用Java，主要框架springboot，开发工具idea，数据库需要用到jdbc和mybaits，小程序所使用的程序文件类型大致分为以下几种：WXML(WeiXin Mark Language，微信标记语言)、WXSS(WeiXin Style Sheet，微信样式表)、JS(Java，小程序的主体)

**Comment by Guiyuuu** [comment]
前端可以使用uni-app框架，uni-app使用vue.js开发，vue语法基于HTML的模板。用表单收集信息、JavaScript、css等。小程序的API组件里面有很多现成的交互方法。

**Comment by z20001** [comment]
微信小程序前端开发需要掌握html、css和js这三种基础语言，并了解微信使用的wxml,wxss，可以使用WeUI 小程序的基础样式库和微信UI组件库 iView Weapp，清楚数据与逻辑之间的关系。由于需要学习很多新的UI框架和技术，还是有一定的难度。

**Comment by computer-rookie-master** [comment]
https://user-images.githubusercontent.com/87467455/139678664-847fae0f-1a3f-47fc-854a-b6e3d08ffc96.mp4
