### ISSUE TITLE
编码规范完成、平台环境搭建完成、初步架构搭建

### ISSUE THREAD

**Issue by computer-rookie-master** [ChatTom-cats/ChatTom#4]

**Comment by Hlq0710** [comment]
前端使用微信开发者工具实现或使用第三方软件，搭配后端使用的IDEA2019.3，后端使用Java语言，数据库使用mysql

**Comment by Xguo-ougX** [comment]
前端使用微信开发者工具或是使用其他第三方工具实现，后端开发环境基于IDEA2019，数据库使用mysql

**Comment by gsoidgsug** [comment]
前端使用微信开发者工具或是使用其他第三方工具实现，后端开发环境基于IDEA2019，数据库使用mysql

**Comment by Guiyuuu** [comment]
前端使用微信开发者工具同时与IDEA进行配合，界面使用Axure设计。后端使用java语言，基于SSM搭建，同时使用mysql进行数据库链接。

**Comment by z20001** [comment]
前端使用微信开发者工具实现，搭配后端使用的IDEA2019.3，后端使用Java语言，数据库使用mysql

**Comment by Xguo-ougX** [comment]
[编码规范.docx](https://github.com/ChatTom-cats/ChatTom/files/7453697/default.docx)
