### ISSUE TITLE
架构设计，WBS，团队成员估计各自任务所需时间

### ISSUE THREAD

**Issue by computer-rookie-master** [ChatTom-cats/ChatTom#5]

**Comment by Xguo-ougX** [comment]
前端可分为美工，页面设计，以及代码实现，后端可分为数据处理，架构搭建，代码实现等等。任务完成需要在12-13周完成。

**Comment by Hlq0710** [comment]
后端编写代码，搭建架构、数据库等，需要在12-14周完成，测试点：授权、功能、缓存、性能、分享功能、层级等，需要在10-14周完成。

**Comment by gsoidgsug** [comment]
后端根据功能来处理数据，编写代码，搭建架构等，需要在12-14周完成

**Comment by Guiyuuu** [comment]
每个WBS项应该进行文档化，以确保准确理解已包括和未包括的工作范围。前端尽可能直接使用微信提供的API接口进行，界面设计美观便捷。任务完成需要在12-13周完成。

**Comment by computer-rookie-master** [comment]
主要负责后端的搭建以及整个队伍进展的控制，因为对项目进程还不熟悉，目标在14周前完成

**Comment by z20001** [comment]
进行WBS工作拆分，可以更加清晰地知道每个阶段要做的任务，也可以更好地分配任务。微信前端设计要注意微信接口和缓存的问题，要进行页面设计和美工，界面需要美观且直观。任务初判断在12-13周完成。

**Comment by computer-rookie-master** [comment]
![image](https://user-images.githubusercontent.com/87467455/139680171-c93db2cb-dc31-497e-bb75-729ef3cafd67.png)
