### ISSUE TITLE
测试计划制定

### ISSUE THREAD

**Issue by computer-rookie-master** [ChatTom-cats/ChatTom#6]

**Comment by Hlq0710** [comment]
后端编写主要用Java，主要框架springboot，数据库需要用到jdbc和mybaits，mybaits以映射sql语句orm方式来数据库持久化操作。

**Comment by gsoidgsug** [comment]
测试方案
小程序虽然是微信推出的新形态产品，但是在测试思路上跟其他客户端测试在模式上也有类似之处。小程序的测试主要分为以下几个方面，即功能测试、兼容性测试、性能测试、后台接口测试、安全测试、组件测试。

1、功能测试

功能测试跟传统web端的测试类似。用例设计方法等跟需求相关性较大。后续会详细写需求以及功能测试方面的测试分析。

2、兼容性测试

小程序的兼容性比传统的APP兼容性测试考虑方面会多一点，最好从机型、操作系统、分辨率、微信版本、数据这几个方面去考虑小程序的兼容性。

操作系统兼容性：因为Android和iOS系统上小程序的JavaScript脚本执行的环境不同，所以存在操作系统兼容性。官方文档中说明，在开发工具上，小程序的js代码时运行在nwjs中，在iOS上是运行在JavaScriptCore中，在Android上是通过X5JSCore来解析的。正因为脚本执行的环境不同，因此在开发工具上正常的小程序有可能在Android和iOS系统上不符合预期。

机型、分辨率和系统版本：小程序部分api依赖于系统底层实现，以及JavaScript标准库也与系统版本强关联，所以尤其是安卓设备，在兼容性方面尤其要注意。

微信兼容性：微信版本的兼容性主要体现在小程序api库的版本上。有些比较老的版本小程序api库不支持新版的api库，因此会出现兼容性问题。所以测试微信版本的兼容性之前要先确定小程序使用的库版本在哪些微信版本上支持。

缓存数据兼容性：由于小程序在使用过程中可能会缓存部分数据，在新版本中，数据可能会被重新使用。如果存在数据不兼容，会出现非预期行为。

发布兼容性：最新微信客户端中小程序基础库发布有个灰度过程，一般为12个小时，API新老版本兼容。
针对以上方面的兼容，我们制定一个兼容性的标准。标准数据可以通过以下渠道获取：操作系统兼容性可以通过埋点进行收集，而微信兼容性可以通过埋点或者小程序管理后台查看近30天内访问当前小程序的用户所使用的基础库版本占比。

兼容性标准制定以后，主要通过以下3种方式进行兼容性测试。

1）Top10机型和微信客户端组合手工兼容（通过长按删除微信小程序清理缓存方式，进行新安装及覆盖安装的数据兼容性测试）
2）开发版本可以通过微信开发者工具提交远程真机随机测试（4-8台远程真机，免费，1天只能提交一次，追求最大覆盖页面算法）
3）外部兼容测试服务。

3、性能测试

这里性能测主要考虑的是客户端的性能。服务器性能则按照传统的服务器性能测试方案即可。小程序客户端的性能和网页的性能测试非常类似，性能指标也大致相同。比如页面的白屏时间，首屏时间，资源占用，页面渲染时间等等。

小程序的开发工具提供了手动查看性能的窗口，只要在小程序开发版中打开性能窗口即可查看性能数据。所以性能测试可以考虑以性能埋点上报的方式进行性能分析，上报时区分测试环境和运营环境。发布前现在测试环境分析各个页面的耗时，及时发现页面的性能问题。

4、接口测试

小程序的后台接口测试跟其他的客户端接口测试类似，直接照常规的后台接口测试展开即可。后续会详细写接口方面的测试分析。

5、组件测试

由于在实际业务开发中，开发可能需要自定义组件支持，这就需要涉及组件测试，可以通过node+jest+miniprogram-simulate完成组件功能的测试，由于有一定的入门门槛，建议由开发完成。

6、安全测试

对于安全性测试来说，由于小程序集成在微信客户端内，相比于传统的网页来说，安全性能够更有保障，只要在后台接口测试上保证数据的安全性，客户端的安全性由微信app来帮我们保证。​

**Comment by gsoidgsug** [comment]
[测试方案.docx](https://github.com/ChatTom-cats/ChatTom/files/7452898/default.docx)
